### PR TITLE
Add dependencies to setup.py

### PR DESCRIPTION
**Pull request by nczita**
It's not obvius when installing from pip to add those dependencies.
I think that having them in setup.py will make instalation straightforward.

### CODE REVIEW

**Comment by robooo** [comment]
Personally I would prefer to leave avro optional like [here](https://github.com/confluentinc/confluent-kafka-python/blob/master/setup.py#L92). You don't need to always install avro. 
+ same for test dependencies

**Comment by nczita** [comment]
Unfortunately, it would require some changes to make those dependencies optional, as there are used in:
- https://github.com/robooo/robotframework-ConfluentKafkaLibrary/blob/master/src/ConfluentKafkaLibrary/consumer.py#L6 (AvroConsumer)
- https://github.com/robooo/robotframework-ConfluentKafkaLibrary/blob/master/src/ConfluentKafkaLibrary/__init__.py#L88 (SchemaRegistryClient)

So as far I understand AvroConsumer requires: `avro-python3` and `fastavro`, while the SchemaRegistryClient requires: `requests` and `jsonschema`. To make them optional would require small refactoring to remove them as a dependency, I would be happy to help with that but it would require more time. 

The proposed change would make the instalation work "out of the box" ;) 

PS. I will add a small sleep or some kind of entrypoint that wait some time for docker containers to be functional :D

**Comment by robooo** [comment]
Thank you for the contribution ;) is it complete to merge it from your side?
I've created the issue and will prepare release with latest changes soon.

**Comment by nczita** [comment]
Yes sure ;) If you don't mind please use "Squash and Commit", so I wouldn't have to force push "one commit" update ;) 
As there was some mine misunderstanding about how Travis is working.

**Pull request merged**
